### ISSUE TITLE
A few errors on systemd unit

### ISSUE THREAD

**Issue by f-izzo** [aaronpuchert/throttle#1]
Tested on Ubuntu 16.04.4 LTS server
Problems found:
- the group `users` does not exist by default
- `chown` path is `/bin/chown`, not  `/usr/bin/chown`
- `rm` path is `/bin/rm`, not  `/usr/bin/rm`

**Comment by aaronpuchert** [comment]
Thanks for trying this out on another distribution. I only ever tested this on openSUSE, and I haven't used it for a while.

The `chown root:users PIPE` is about allowing users access to the command pipe. If you don't want that or have a different group of users that should be able to access the pipe, you can just change or remove the line. I think `users` should be available on desktop systems, but maybe not on servers.

I guess what you wrote about `rm` and `chown` also applies to `chmod` then? I'm applying it there as well.
